"use client";
import { useEffect, useState, type ReactNode } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { parseCSV, invoiceTotals } from '@/lib/basic-values.mjs';
// Dynamic records are JSON responses from the validated Basic API.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Row = Record<string, any>;
const today=()=>new Date().toISOString().slice(0,10);
const pounds=(s:unknown)=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(Number(s??0));
async function api(op:string,body:Row={}){const r=await fetch('/api/basic',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,op})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed.');return data;}
function Field({label,name,value='',type='text',required=false}:{label:string;name:string;value?:string;type?:string;required?:boolean}){return <label className="basic-field">{label}<Input name={name} defaultValue={value} type={type} required={required} step={type==='number'?'0.01':undefined}/></label>}
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][]}){return <label className="basic-field">{label}<select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Modal({title,children,close}:{title:string;children:ReactNode;close:()=>void}){return <Dialog open onOpenChange={v=>!v&&close()}><DialogContent className="basic-dialog"><DialogHeader><DialogTitle>{title}</DialogTitle><DialogDescription>Keep your business records up to date.</DialogDescription></DialogHeader>{children}</DialogContent></Dialog>}
function Table({headers,children}:{headers:string[];children:ReactNode}){return <div className="table-wrap basic-table" tabIndex={0} role="region" aria-label="Records; scroll for additional columns"><table><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
export function BasicModule({section,business,onAccountingChange}:{section:string;business:{name:string};onAccountingChange:()=>void}){
 const [data,setData]=useState<Row>({contacts:[],invoices:[],accounts:[],entries:[]}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [edit,setEdit]=useState<Row|null>(null),[detail,setDetail]=useState<Row|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('active'),[accountId,setAccountId]=useState(''),[bank,setBank]=useState<Row|null>(null),[importing,setImporting]=useState(false),[transaction,setTransaction]=useState<Row|null>(null);
 async function load(){const r=await fetch('/api/basic');const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);if(accountId)setBank(await api('bank.list',{account_id:accountId}));}
 useEffect(()=>{let alive=true;fetch('/api/basic').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);if(alive)setData(d);}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false;};},[]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await action();await load();onAccountingChange();}catch(e){setError(e instanceof Error?e.message:'Could not save.');}finally{setBusy(false);}}
 const matches=(r:Row)=>Object.values(r).some(v=>typeof v==='string'&&v.toLowerCase().includes(query.toLowerCase()));
 async function viewInvoice(id:string){setDetail(await api('invoice.get',{id}));}
 const contacts=data.contacts.filter((r:Row)=>matches(r)&&(filter==='all'||filter==='archived'?filter==='all'||r.archived:!r.archived&&(filter==='active'||r.type===filter||r.type==='both')));
 return <div className="basic-module" aria-busy={busy}>
 <div className="page-heading"><div><p className="eyebrow">My business</p><h1>{section}</h1><p>{section==='Contacts'?'Keep customer and supplier details together.':section==='Invoices'?'Create invoices and record payments.':'Import statements and match your business transactions.'}</p></div><Button disabled={busy} onClick={()=>setEdit({})}>Add {section==='Contacts'?'contact':section==='Invoices'?'invoice':'bank account'}</Button></div>
 {error&&<p className="form-error basic-alert" role="alert">{error}</p>}{notice&&<p className="basic-alert" role="status">{notice}</p>}
 {loading?<p role="status">Loading your records…</p>:<>
 {section!=='Banking'&&<div className="table-tools"><Input aria-label={`Search ${section}`} placeholder={`Search ${section.toLowerCase()}…`} value={query} onChange={e=>setQuery(e.target.value)}/><Choice label="Filter" value={filter} onChange={setFilter} options={section==='Contacts'?[['active','Active'],['customer','Customers'],['supplier','Suppliers'],['archived','Archived'],['all','All']]:[['active','All'],['draft','Draft'],['sent','Sent'],['paid','Paid'],['overdue','Overdue'],['cancelled','Cancelled']]}/></div>}
 {section==='Contacts'&&<section className="panel">{!contacts.length?<div className="empty-transactions"><b>{data.contacts.length?'No matching contacts':'No contacts yet'}</b><p>Add your first customer or supplier</p></div>:<Table headers={['Contact','Company','Type','Email','Actions']}>{contacts.map((c:Row)=><tr key={c.id}><td>{c.name}</td><td>{c.company}</td><td>{c.type}{c.archived?' · archived':''}</td><td>{c.email}</td><td><div className="basic-actions"><Button variant="outline" onClick={()=>setDetail({contact:c})}>View</Button><Button variant="outline" onClick={()=>setEdit(c)}>Edit</Button><Button disabled={busy} variant="outline" onClick={()=>run(async()=>{await api('contact.archive',{id:c.id,archived:!c.archived});})}>{c.archived?'Restore':'Archive'}</Button></div></td></tr>)}</Table>}</section>}
 {section==='Invoices'&&<section className="panel">{!data.invoices.length?<div className="empty-transactions"><b>No invoices yet</b><p>Add a customer in Contacts, then create your first invoice.</p></div>:<Table headers={['Number','Customer','Due','Status','Total','Actions']}>{data.invoices.filter((i:Row)=>matches(i)&&(filter==='active'||filter===i.display_status)).map((i:Row)=><tr key={i.id}><td className="basic-number">{i.invoice_number}</td><td>{i.customer}</td><td>{i.due_date}</td><td><span className="status-badge">{i.display_status.toUpperCase()}</span></td><td>{pounds(i.amount)}</td><td><div className="basic-actions"><Button variant="outline" disabled={busy} onClick={()=>run(()=>viewInvoice(i.id))}>View</Button>{i.status==='draft'&&<><Button variant="outline" disabled={busy} onClick={()=>run(async()=>setEdit(await api('invoice.get',{id:i.id})))}>Edit</Button><Button variant="outline" disabled={busy} onClick={()=>{if(confirm('Delete this draft invoice?'))void run(async()=>{await api('invoice.delete',{id:i.id});});}}>Delete draft</Button></>}</div></td></tr>)}</Table>}</section>}
 {section==='Banking'&&<><p className="basic-alert">Manual statement records · GBP only. The calculated book balance is not a live bank balance. Opening balance is the balance immediately before transactions on the opening date.</p><section className="panel"><div className="table-tools"><Choice label="Bank account" value={accountId} onChange={id=>{setAccountId(id);setBank(null);if(id)void api('bank.list',{account_id:id}).then(setBank).catch(e=>setError(e.message));}} options={[["","Choose an account"],...data.accounts.map((a:Row)=>[a.id,a.name+(a.archived?' (archived)':'')] as [string,string])]}/>{accountId&&<><Button variant="outline" onClick={()=>setEdit(data.accounts.find((a:Row)=>a.id===accountId))}>Edit account</Button><Button disabled={busy} variant="outline" onClick={()=>run(async()=>{const a=data.accounts.find((a:Row)=>a.id===accountId);await api('account.archive',{id:accountId,archived:!a.archived});})}>{data.accounts.find((a:Row)=>a.id===accountId)?.archived?'Restore':'Archive'}</Button></>}</div>{!data.accounts.length&&<div className="empty-transactions"><b>No bank accounts yet</b><p>Add an account to import your first statement.</p></div>}</section>
 {bank&&<><div className="metric-grid three">{[['Calculated book balance',bank.balance],['Imported money in',bank.money_in],['Imported money out',bank.money_out]].map(([label,value])=><article className="metric green" key={label}><span>{label}</span><strong>{pounds(value)}</strong></article>)}</div><section className="panel"><div className="panel-heading"><div><h2>{bank.account.name}</h2><p>{bank.transactions.filter((t:Row)=>t.status==='UNREVIEWED').length} unreviewed · {bank.transactions.filter((t:Row)=>t.status==='RECONCILED').length} reconciled</p></div><Button disabled={busy||!!bank.account.archived} onClick={()=>setImporting(true)}>Import CSV</Button></div><Table headers={['Date','Description','Amount','Category','Status','Action']}>{bank.transactions.map((t:Row)=><tr key={t.id}><td>{t.transaction_date}</td><td>{t.description}</td><td>{pounds(t.amount)}</td><td>{t.category||t.classification||'Uncategorised'}</td><td>{t.status}</td><td><Button variant="outline" disabled={busy||t.status==='RECONCILED'||!!bank.account.archived} onClick={()=>setTransaction(t)}>Review</Button></td></tr>)}</Table>{!bank.transactions.length&&<p className="table-empty">No transactions yet. Import a CSV statement.</p>}</section></>}
 </>}
 </>}
 {edit&&<Modal title={` ${edit.id||edit.invoice?'Edit':'Add'} ${section==='Contacts'?'contact':section==='Invoices'?'invoice':'bank account'}`} close={()=>!busy&&setEdit(null)}><fieldset disabled={busy} className="basic-fieldset">{section==='Contacts'?<ContactForm row={edit} save={async fields=>run(async()=>{await api('contact.save',{...fields,id:edit.id});setEdit(null);})}/>:section==='Invoices'?<InvoiceForm data={edit} contacts={data.contacts} save={async fields=>run(async()=>{await api('invoice.save',fields);setEdit(null);})}/>:<AccountForm row={edit} save={async fields=>run(async()=>{await api('account.save',{...fields,id:edit.id});setEdit(null);})}/>}</fieldset>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
 {detail?.contact&&<Modal title={detail.contact.name} close={()=>setDetail(null)}><dl className="basic-contact">{Object.entries({...detail.contact,...JSON.parse(detail.contact.address||'{}')}).filter(([k])=>!['id','user_id','business_id','address'].includes(k)).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{String(v??'—')}</dd></div>)}</dl></Modal>}
 {detail?.invoice&&<Modal title="Invoice" close={()=>!busy&&setDetail(null)}><InvoiceView detail={detail} business={business} busy={busy} change={async fields=>run(async()=>{await api('invoice.status',{id:detail.invoice.id,...fields});await viewInvoice(detail.invoice.id);})}/>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
 {importing&&<Modal title="Import bank statement" close={()=>!busy&&setImporting(false)}><ImportForm busy={busy} accountId={accountId} execute={run} done={()=>{setImporting(false);setNotice('Statement imported. Review and reconcile each transaction below.');}}/>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
 {transaction&&<Modal title="Review transaction" close={()=>!busy&&setTransaction(null)}><ReviewForm busy={busy} transaction={transaction} entries={data.entries} save={fields=>run(async()=>{await api('bank.process',{...fields,id:transaction.id,account_id:accountId});setTransaction(null);})}/>{error&&<p className="form-error" role="alert">{error}</p>}</Modal>}
 </div>;
}
function ContactForm({row,save}:{row:Row;save:(v:Row)=>Promise<void>}){const [type,setType]=useState(row.type||'customer');const address=JSON.parse(row.address||'{}');return <form className="entry-form" action={async f=>{const v=Object.fromEntries(f);await save({...v,type,address:Object.fromEntries(['line1','line2','city','county','postcode','country'].map(k=>[k,v[k]]))});}}><div className="basic-grid"><Field label="Contact/person name" name="name" value={row.name} required/><Field label="Company" name="company" value={row.company}/><Choice label="Type" value={type} onChange={setType} options={['customer','supplier','both'].map(s=>[s,s])}/><Field label="Email" name="email" type="email" value={row.email}/><Field label="Telephone" name="telephone" value={row.telephone}/>{[['line1','Address line 1'],['line2','Address line 2'],['city','Town/city'],['county','County'],['postcode','Postcode'],['country','Country']].map(([k,l])=><Field key={k} label={l} name={k} value={address[k]||''}/>)}</div><label className="basic-field">Notes<textarea name="notes" defaultValue={row.notes||''}/></label><Button type="submit">Save contact</Button></form>}
function AccountForm({row,save}:{row:Row;save:(v:Row)=>Promise<void>}){const [type,setType]=useState(row.account_type||'Current');return <form className="entry-form" action={async f=>save({...Object.fromEntries(f),account_type:type,currency:'GBP'})}><div className="basic-grid"><Field label="Account name" name="name" value={row.name} required/><Field label="Bank name" name="bank_name" value={row.bank_name}/><Field label="Last four digits / reference (optional)" name="reference" value={row.reference}/><Choice label="Account type" value={type} onChange={setType} options={['Current','Savings','Cash','Credit card'].map(s=>[s,s])}/><Field label="Opening balance (£)" name="opening_balance" value={row.opening_balance||'0.00'} required/><Field label="Opening balance date" name="opening_date" type="date" value={row.opening_date||today()} required/></div><p>Currency: GBP. Opening balance is locked after importing transactions.</p><Button type="submit">Save account</Button></form>}
const blankLine=()=>({description:'',quantity:'1',unit_price:'0.00',tax_rate:'0'});
function InvoiceForm({data,contacts,save}:{data:Row;contacts:Row[];save:(v:Row)=>Promise<void>}){
 const row=data.invoice||{},[customer,setCustomer]=useState(row.contact_id||''),[items,setItems]=useState<Row[]>(data.items?.length?data.items:[blankLine()]);let totals:Row|null=null;try{totals=invoiceTotals(items);}catch{}
 return <form className="entry-form" action={async f=>save({...Object.fromEntries(f),id:row.id,contact_id:customer,items})}><Choice label="Customer" value={customer} onChange={setCustomer} options={[["","Select customer"],...contacts.filter(c=>!c.archived&&c.type!=='supplier').map(c=>[c.id,c.company||c.name] as [string,string])]}/><div className="basic-grid"><Field label="Issue date" name="issue_date" type="date" value={row.issue_date||today()} required/><Field label="Due date" name="due_date" type="date" value={row.due_date||today()} required/><Field label="Reference" name="reference" value={row.reference}/></div><p>Enter prices before VAT. Leave VAT at 0 unless applicable. Totals are recalculated on the server.</p>{items.map((line,n)=><div key={n} className="invoice-line">{[['description','Description'],['quantity','Quantity'],['unit_price','Unit price (£)'],['tax_rate','VAT (%)']].map(([k,label])=><label className="basic-field" key={k}>{label}<Input required value={line[k]} onChange={e=>setItems(items.map((l,index)=>index===n?{...l,[k]:e.target.value}:l))}/></label>)}<Button type="button" variant="outline" disabled={items.length===1} onClick={()=>setItems(items.filter((_,index)=>index!==n))}>Remove line {n+1}</Button></div>)}<Button type="button" variant="outline" disabled={items.length>=100} onClick={()=>setItems([...items,blankLine()])}>Add line</Button>{totals?<p>Subtotal {pounds(totals.subtotal)} · VAT {pounds(totals.tax_total)} · <b>Total {pounds(totals.amount)}</b></p>:<p>Complete each line with valid quantities and amounts.</p>}<label className="basic-field">Notes<textarea name="notes" defaultValue={row.notes||''}/></label><Button type="submit" disabled={!customer||!totals}>Save draft</Button></form>
}
function InvoiceView({detail,business,busy,change}:{detail:Row;business:{name:string};busy:boolean;change:(v:Row)=>Promise<void>}){
 const i=detail.invoice,c=JSON.parse(i.customer_snapshot||'{}'),a=JSON.parse(c.address||'{}'),[paidDate,setPaidDate]=useState(today());const overdue=i.status==='sent'&&i.due_date<today();
 return <><article className="invoice-print"><header><h2>{business.name}</h2><h2>INVOICE</h2></header><p className="basic-number">{i.invoice_number}</p><p>Status: {(overdue?'overdue':i.status).toUpperCase()}</p><div className="basic-grid"><div><b>Bill to</b><p>{i.customer}</p><p>{c.name}</p>{Object.values(a).filter(Boolean).map((v,n)=><p key={n}>{String(v)}</p>)}<p>{c.email}</p></div><div><p>Issued: {i.issue_date}</p><p>Due: {i.due_date}</p><p>Reference: {i.reference||'—'}</p></div></div><Table headers={['Description','Quantity','Price','VAT %','Net','VAT']}>{detail.items.map((l:Row)=><tr key={l.id}><td>{l.description}</td><td>{l.quantity}</td><td>{pounds(l.unit_price)}</td><td>{l.tax_rate}</td><td>{pounds(l.net)}</td><td>{pounds(l.tax)}</td></tr>)}</Table><div className="report-lines"><div>Subtotal <b>{pounds(i.subtotal)}</b></div><div>VAT <b>{pounds(i.tax_total)}</b></div><div className="report-total">Total GBP <b>{pounds(i.amount)}</b></div></div><p className="basic-notes">{i.notes}</p>{detail.payments.map((p:Row)=><p key={p.id}>Paid {pounds(p.amount)} on {p.payment_date} · Sale reference: {p.entry_id}</p>)}</article><div className="basic-actions no-print"><Button variant="outline" onClick={()=>window.print()}>Print / save PDF</Button>{i.status==='draft'&&<Button disabled={busy} onClick={()=>change({status:'sent'})}>Mark sent</Button>}{i.status==='sent'&&<><label className="basic-field">Payment date<Input type="date" max={today()} min={i.issue_date} value={paidDate} onChange={e=>setPaidDate(e.target.value)}/></label><Button disabled={busy} onClick={()=>change({status:'paid',payment_date:paidDate})}>Mark paid & create sale</Button></>}{['draft','sent'].includes(i.status)&&<Button variant="outline" disabled={busy} onClick={()=>{if(confirm('Cancel this invoice?'))void change({status:'cancelled'});}}>Cancel invoice</Button>}</div><p className="no-print">Mark sent records its status; share the printed PDF yourself. Recording payment creates a Sale. Match the imported bank payment to that Sale.</p></>
}
function ImportForm({accountId,busy,execute,done}:{accountId:string;busy:boolean;execute:(f:()=>Promise<void>)=>Promise<void>;done:()=>void}){
 const [csv,setCSV]=useState(''),[rows,setRows]=useState<string[][]>([]),[mapping,setMapping]=useState<Row>({date:-1,description:-1,amount:-1,money_in:-1,money_out:-1}),[mode,setMode]=useState('amount'),[preview,setPreview]=useState<Row[]|null>(null),[decisions,setDecisions]=useState<Row>({});
 const actual={...mapping,...(mode==='amount'?{money_in:-1,money_out:-1}:{amount:-1})};
 return <fieldset disabled={busy} className="entry-form basic-fieldset"><label className="basic-field">CSV statement (maximum 2 MB)<Input type="file" accept=".csv,text/csv" onChange={e=>{const file=e.target.files?.[0];if(file)void execute(async()=>{if(file.size>2000000)throw new Error('CSV must be under 2 MB.');const source=await file.text();const parsed=parseCSV(source);setCSV(source);setRows(parsed);setPreview(null);setDecisions({});});}}/></label>{rows.length>0&&<><h3>File preview</h3><Table headers={rows[0].map((h,n)=>`${n+1}. ${h}`)}>{rows.slice(1,6).map((r,n)=><tr key={n}>{r.map((v,j)=><td key={j}>{v}</td>)}</tr>)}</Table><Choice label="Amount format" value={mode} onChange={v=>{setMode(v);setPreview(null);}} options={[["amount","Signed amount (negative = money out)"],["split","Separate money in / money out"]]}/><div className="basic-grid">{['date','description',...(mode==='amount'?['amount']:['money_in','money_out'])].map(k=><Choice key={k} label={k.replaceAll('_',' ')} value={String(mapping[k])} onChange={v=>{setMapping({...mapping,[k]:Number(v)});setPreview(null);setDecisions({});}} options={[["-1","Select column"],...rows[0].map((h,n)=>[String(n),`${n+1}. ${h}`] as [string,string])]}/>)}</div><p>Dates: YYYY-MM-DD or UK DD/MM/YYYY (also dots or hyphens). Duplicate candidates require an explicit decision.</p><Button onClick={()=>execute(async()=>{const d=await api('bank.preview',{account_id:accountId,csv,mapping:actual});setPreview(d.rows);setDecisions({});})}>Validate & preview import</Button></>}{preview&&<><p>{preview.length} validated rows · {preview.filter(r=>r.duplicate).length} possible duplicates</p><Table headers={['Row','Date','Description','Amount','Review']}>{preview.map(r=><tr key={r.row}><td>{r.row}</td><td>{r.transaction_date}</td><td>{r.description}</td><td>{pounds(r.amount)}</td><td>{r.duplicate?<Choice label="Possible duplicate" value={decisions[r.row]||''} onChange={v=>setDecisions({...decisions,[r.row]:v})} options={[["","Choose"],["skip","Skip duplicate"],["keep","Keep as separate transaction"]]}/>:<span>New transaction</span>}</td></tr>)}</Table><Button disabled={preview.some(r=>r.duplicate&&!decisions[r.row])} onClick={()=>execute(async()=>{await api('bank.import',{account_id:accountId,csv,mapping:actual,decisions});done();})}>Confirm import</Button></>}</fieldset>
}
function ReviewForm({transaction:t,entries,busy,save}:{transaction:Row;entries:Row[];busy:boolean;save:(v:Row)=>Promise<void>}){
 const [mode,setMode]=useState(t.entry_id?'match':t.classification||'uncategorised'),[entryId,setEntryId]=useState(t.entry_id||'');const candidates=entries.filter(e=>e.kind===(Number(t.amount)>0?'sale':'expense')&&Math.abs(Number(t.amount))===Number(e.amount));
 return <form className="entry-form" action={async f=>save({...Object.fromEntries(f),classification:mode,entry_id:entryId,reconcile:f.get('reconcile')==='on'})}><fieldset disabled={busy} className="entry-form basic-fieldset"><p>{t.transaction_date} · {t.description} · <b>{pounds(t.amount)}</b></p><Choice label="Classification" value={mode} onChange={setMode} options={t.entry_id?[['match','Keep linked accounting entry']]:[['uncategorised','Leave uncategorised'],['match','Match existing sale / expense'],['create','Create sale / expense'],['transfer','Transfer (no income / expense)'],['ignore','Ignore / non-business']]}/>{mode==='match'&&<Choice label="Accounting entry (same amount)" value={entryId} onChange={setEntryId} options={[["","Choose entry"],...(t.entry_id?[[t.entry_id,'Current linked entry'] as [string,string]]:[]),...candidates.map(e=>[e.id,`${e.entry_date} · ${e.party} · ${e.description}`] as [string,string])]}/>}<Field label="Category" name="category" value={t.category||''} required={mode==='create'}/>{mode==='create'&&<><Field label={Number(t.amount)>0?'Customer':'Supplier'} name="party" required/><p>Creates a new accounting entry with VAT £0. For VAT-bearing entries, record the Sale/Expense first and match it here.</p></>}<label><input type="checkbox" name="reconcile" disabled={mode==='uncategorised'}/> Mark reconciled (locks this transaction)</label><Button type="submit" disabled={mode==='match'&&!entryId}>Save review</Button></fieldset></form>
}
